# Generated by Django 4.0 on 2022-05-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('product_name', models.CharField(max_length=50)),
                ('product_quantity', models.IntegerField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_discription', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
