# Generated by Django 4.0.4 on 2022-05-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_product_rename_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.ImageField(null=True, upload_to='')),
                ('lastname', models.CharField(max_length=50)),
                ('sallary', models.IntegerField(max_length=50)),
                ('mobnumber', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
