# Generated by Django 4.0.4 on 2022-05-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sallary',
            field=models.IntegerField(),
        ),
    ]
