# Generated by Django 4.0.4 on 2022-06-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0008_order_product_quantity_alter_order_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
