# Generated by Django 4.0.4 on 2022-06-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0009_alter_order_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
