version: '3.10'

# services:
#     app:
#         build: .
#         volumes:
#             - .:/dashboard
#         ports:
#             - 8000:8000
#         image: app:dashboard
#         container_name: dashboard_container
#         command: python manage.py  runserver 0.0.0.0:8000



services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.8000
        volumes:
            - .:/dashboard
        ports:
            - "8000:8000"
        depends_on:
            -dashboard
    dashboard:
              image: mysql
              container_name: dashboard
              enviroment:
                  - MYSQL_DB=dashboard
                  - MYSQL_USER=root
                  - MYSQL_PASSWORD=""




    # volumes:
    #    - .:/dashboard
    # command: python manage.py runserver 0.0.0.0.8000
    # ports:
    #     - 8000:8000
    # image: app:dashboard
    # container_name: dashboard_container